name = "Create Techified"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "493faa59fd60621c0d456024f7349e8583e61f61b19d1663666f77a1e5e7f32e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
