name = "Create Techified"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4c3cbc82af33aa73eaad5fec9fec72bab2337ce27dcafabc3cf441f001c84a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
